function(cpprest_find_websocketpp)
	if(NOT TARGET cpprestsdk_websocketpp_internal)
		find_package(websocketpp CONFIG REQUIRED)
		add_library(cpprestsdk_websocketpp_internal INTERFACE)
		target_link_libraries(cpprestsdk_websocketpp_internal INTERFACE websocketpp::websocketpp)
	endif()
endfunction()
