function(cpprest_find_zlib)
	if(NOT TARGET cpprestsdk_zlib_internal)
		find_package(ZLIB CONFIG REQUIRED)
		add_library(cpprestsdk_zlib_internal INTERFACE)
		target_link_libraries(cpprestsdk_zlib_internal INTERFACE ZLIB::ZLIB)
		# target_include_directories(cpprestsdk_zlib_internal INTERFACE "${CONAN_INCLUDE_DIRS_OPENSSL}")
		# target_link_libraries(cpprestsdk_zlib_internal INTERFACE "${CONAN_LIBS_OPENSSL}")
	endif()
endfunction()
