function(cpprest_find_openssl)
	if(NOT TARGET cpprestsdk_openssl_internal)
		find_package(OpenSSL CONFIG REQUIRED)
		add_library(cpprestsdk_openssl_internal INTERFACE)
		target_link_libraries(cpprestsdk_openssl_internal INTERFACE OpenSSL::OpenSSL)
	endif()
endfunction()
