macro(cpprestsdk_find_boost_android_package)
  # set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
  # set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
  # set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  # if(CMAKE_HOST_WIN32)
  #   set(WIN32 1)
  #   set(UNIX)
  # elseif(CMAKE_HOST_APPLE)
  #   set(APPLE 1)
  #   set(UNIX)
  # endif()
  # find_package(${ARGN})
  # set(APPLE)
  # set(WIN32)
  # set(UNIX 1)
  # set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  # set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  # set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
endmacro()

function(cpprest_find_boost)
	if(NOT TARGET cpprestsdk_boost_internal)
		find_package(Boost CONFIG REQUIRED)
		add_library(cpprestsdk_boost_internal INTERFACE)
		target_link_libraries(cpprestsdk_boost_internal INTERFACE Boost::Boost)
	endif()
endfunction()
