function(cpprest_find_winhttppal)
	if(NOT TARGET cpprestsdk_winhttppal_internal)
		find_package(todo CONFIG REQUIRED)
		add_library(cpprestsdk_winhttppal_internal INTERFACE)
		target_link_libraries(cpprestsdk_winhttppal_internal INTERFACE todo::todo)
	endif()
endfunction()
